server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:55432/inventory_db}
    username: ${INVENTORY_DB_USER:cloud}
    password: ${INVENTORY_DB_PASSWORD:cloud}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:cloud}
    password: ${RABBITMQ_PASSWORD:cloud}
    template:
      observation-enabled: true
    listener:
      simple:
        observation-enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2s

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  pattern:
    level: "%5p [trace_id=%X{trace_id:-}]"

app:
  messaging:
    exchange: ecom.events
    retry-exchange: inventory.retry.exchange
    dlq-exchange: inventory.dlq.exchange
    queues:
      order-created: q.inventory.order-created
      order-created-retry: q.inventory.order-created.retry
      order-created-dlq: q.inventory.order-created.dlq
      release-requested: q.inventory.release-requested
      release-requested-retry: q.inventory.release-requested.retry
      release-requested-dlq: q.inventory.release-requested.dlq
    routing-keys:
      order-created: order.created
      order-created-retry: q.inventory.order-created.retry
      order-created-dlq: q.inventory.order-created.dlq
      release-requested: inventory.release.requested
      release-requested-retry: q.inventory.release-requested.retry
      release-requested-dlq: q.inventory.release-requested.dlq
      inventory-reserved: inventory.reserved
      inventory-released: inventory.released
      inventory-failed: inventory.failed
    retry-ttl-ms: 10000
    max-retries: 3
  cache:
    stock:
      enabled: ${INVENTORY_STOCK_CACHE_ENABLED:true}
      key-prefix: "inventory:stock:"
      ttl-seconds: ${INVENTORY_STOCK_CACHE_TTL_SECONDS:300}
