server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:postgresql://localhost:55432/inventory_db}
    username: ${INVENTORY_DB_USER:cloud}
    password: ${INVENTORY_DB_PASSWORD:cloud}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:cloud}
    password: ${RABBITMQ_PASSWORD:cloud}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  messaging:
    exchange: ecom.events
    retry-exchange: inventory.retry.exchange
    dlq-exchange: inventory.dlq.exchange
    queues:
      order-created: q.inventory.order-created
      order-created-retry: q.inventory.order-created.retry
      order-created-dlq: q.inventory.order-created.dlq
      release-requested: q.inventory.release-requested
      release-requested-retry: q.inventory.release-requested.retry
      release-requested-dlq: q.inventory.release-requested.dlq
    routing-keys:
      order-created: order.created
      order-created-retry: q.inventory.order-created.retry
      order-created-dlq: q.inventory.order-created.dlq
      release-requested: inventory.release.requested
      release-requested-retry: q.inventory.release-requested.retry
      release-requested-dlq: q.inventory.release-requested.dlq
      inventory-reserved: inventory.reserved
      inventory-released: inventory.released
      inventory-failed: inventory.failed
    retry-ttl-ms: 10000
    max-retries: 3
