server:
  port: 8083

spring:
  application:
    name: payment-service
  datasource:
    url: ${PAYMENT_DB_URL:jdbc:postgresql://localhost:55432/payment_db}
    username: ${PAYMENT_DB_USER:cloud}
    password: ${PAYMENT_DB_PASSWORD:cloud}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:cloud}
    password: ${RABBITMQ_PASSWORD:cloud}

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  messaging:
    exchange: ecom.events
    retry-exchange: payment.retry.exchange
    dlq-exchange: payment.dlq.exchange
    queues:
      inventory-reserved: q.payment.inventory-reserved
      inventory-reserved-retry: q.payment.inventory-reserved.retry
      inventory-reserved-dlq: q.payment.inventory-reserved.dlq
    routing-keys:
      inventory-reserved: inventory.reserved
      inventory-reserved-retry: q.payment.inventory-reserved.retry
      inventory-reserved-dlq: q.payment.inventory-reserved.dlq
      payment-succeeded: payment.succeeded
      payment-failed: payment.failed
    retry-ttl-ms: 10000
    max-retries: 3
  payment:
    mock-mode: SUCCESS
    failure-reason: MOCK_DECLINED
